### ISSUE TITLE
cookie command needs to accommodate usernames without an at-sign

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/Rocket-Bot#33]
The cookie command should be able to handle a username that does not start with an @-sign.

This should resolve the following errors:
```2022-10-29T06:38:38.182034003Z ReferenceError: system is not defined
2022-10-29T06:38:38.182091604Z     at Object.exports.run (/usr/src/app/commands/cookie.js:12:19)
2022-10-29T06:38:38.182097835Z     at Client.<anonymous> (/usr/src/app/main.js:135:21)
2022-10-29T06:38:38.182103034Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by KeeperOfMaps** [comment]
Also, documentation for the command should reflect the need for an at-sign.

**Comment by TheRealFakeAdmin** [comment]
> The cookie command should be able to handle a username that does not start with an @-sign.

Sadly, because of the lack of permissions [see `GUILD_MEMBERS` [here](https://discord.com/developers/docs/topics/gateway#privileged-intents)], the bot only has access to the sending user and any mentioned per message. This means the bot cannot convert a text-name to a valid mention.

There is a chance that the bot can just do `@username`, having Discord convert it to a mention, though this needs further testing.

------

> Also, documentation for the command should reflect the need for an at-sign.

Noted. I will add that along with the other fixes.

------

```
2022-10-29T06:38:38.182091604Z     at Object.exports.run (/usr/src/app/commands/cookie.js:12:19)
2022-10-29T06:38:38.182097835Z     at Client.<anonymous> (/usr/src/app/main.js:135:21)
2022-10-29T06:38:38.182103034Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
The error above should not occur either way; I will look into that.

**Comment by TheRealFakeAdmin** [comment]
This was fixed in a recent release. Cookie no longer returns a mention but the nickname, so any input (including mentions) will be returned.
